### PR TITLE
option to hide emoji

### PR DESCRIPTION
**Pull request by danfragoso**
| enabled | disabled |
| --- | --- |
|  Screenshot 2024-02-23 at 10 40 18  |  Screenshot 2024-02-23 at 10 40 23 |

### CODE REVIEW

**Comment by danfragoso** [comment]
@Cardoso222

**Comment by Cardoso222** [comment]
@danfragoso 
Thanks for your PR! That's a great idea!

I think it will be better if we use `.toggleStyle(SwitchToggleStyle(tint: .blue))`
And then put it after the clock name aligned. 

image

**Comment by danfragoso** [comment]
Thanks @Cardoso222, long time no see! I'll do the proposed changes!

**Comment by danfragoso** [comment]
@Cardoso222  🫡
Screenshot 2024-02-27 at 09 34 12

**Comment by Cardoso222** [comment]
Excellent work, it really shines now!

**Pull request merged**
